/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnippetsNewRouteImport } from './routes/snippets/new'
import { Route as SnippetsSnippetIdRouteImport } from './routes/snippets/$snippetId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsNewRoute = SnippetsNewRouteImport.update({
  id: '/snippets/new',
  path: '/snippets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsSnippetIdRoute = SnippetsSnippetIdRouteImport.update({
  id: '/snippets/$snippetId',
  path: '/snippets/$snippetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/snippets/new': typeof SnippetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/snippets/new': typeof SnippetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/snippets/new': typeof SnippetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/snippets/$snippetId'
    | '/snippets/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/sign-in' | '/snippets/$snippetId' | '/snippets/new'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sign-in'
    | '/snippets/$snippetId'
    | '/snippets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SnippetsSnippetIdRoute: typeof SnippetsSnippetIdRoute
  SnippetsNewRoute: typeof SnippetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/new': {
      id: '/snippets/new'
      path: '/snippets/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof SnippetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$snippetId': {
      id: '/snippets/$snippetId'
      path: '/snippets/$snippetId'
      fullPath: '/snippets/$snippetId'
      preLoaderRoute: typeof SnippetsSnippetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SnippetsSnippetIdRoute: SnippetsSnippetIdRoute,
  SnippetsNewRoute: SnippetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
